#Application settings
#How many users per page(default)
usersPerPage: 4

#Logging config
logging:
  level:
    org.springframework.web: ERROR
    com.javidsh: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %clr(%M){red} %clr(%L){yellow} %m%n}"

#JPA/Hibernate config
spring:
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.HSQLDialect
                show_sql: true
                use_sql_comments: true
                format_sql: true
                hbm2ddl:
                    import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
                connection:
                    charSet: UTF-8
                id:
                    new_generator_mappings: false  

#Hibernate config
hibernate:
    hbm2ddl:
        auto: create-drop
                    
